### ISSUE TITLE
使用 gravatar 头像问题

### ISSUE THREAD

**Issue by mugbya** [ericls/FairyBBS#16]
在这儿找到你使用头像的代码： FairyBBS/template/widget/user-panel.html

```
 <img title="{{request.user.profile.username}}" class="avatar-middle" src="{{request.user.profile.avatar.middle}}">
```

但是我 的{{request.user.profile.avatar.middle}} 却获得的是空值... model 跟你写的一样呢，但是django 的版本是1.8

用头像的代码不是很懂....

**Comment by QuietWind** [comment]
这个不是我写的啊 ！
